### ISSUE TITLE
Криво обрезается request.content для лога

### ISSUE THREAD

**Issue by denya** [klen/adrest#7]
Есть мнение, subj.
response.content[:5000]

Если там юникодный контент — то все ложится.
response.content сам по себе имеет тип str.
Предлагаю делать ему .decode('utf-8'), а потом уже резать по длине.
Тем более все-равно в базу оно сохраняется как utf.

Traceback (most recent call last):

 File "/.virtualenv/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
   response = callback(request, _callback_args, *_callback_kwargs)

 File "/.virtualenv/lib/python2.6/site-packages/django/views/generic/base.py", line 47, in view
   return self.dispatch(request, _args, *_kwargs)

 File "/.virtualenv/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 39, in wrapped_view
   resp = view_func(_args, *_kwargs)

 File "/.virtualenv/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 52, in wrapped_view
   return view_func(_args, *_kwargs)

 File "/.virtualenv/lib/python2.6/site-packages/adrest/views.py", line 94, in dispatch
   api_request_finished.send(self, request=self.request, response=response)

 File "/.virtualenv/lib/python2.6/site-packages/django/dispatch/dispatcher.py", line 172, in send
   response = receiver(signal=self, sender=sender, **named)

 File "/.virtualenv/lib/python2.6/site-packages/adrest/models.py", line 48, in save_log
   response = response.content[:5000],

 File "/.virtualenv/lib/python2.6/site-packages/django/db/models/manager.py", line 138, in create
   return self.get_query_set().create(**kwargs)

 File "/.virtualenv/lib/python2.6/site-packages/django/db/models/query.py", line 360, in create
   obj.save(force_insert=True, using=self.db)

 File "/.virtualenv/lib/python2.6/site-packages/django/db/models/base.py", line 460, in save
   self.save_base(using=using, force_insert=force_insert, force_update=force_update)

 File "/.virtualenv/lib/python2.6/site-packages/django/db/models/base.py", line 553, in save_base
   result = manager._insert(values, return_id=update_pk, using=using)

 File "/.virtualenv/lib/python2.6/site-packages/django/db/models/manager.py", line 195, in _insert
   return insert_query(self.model, values, **kwargs)

 File "/.virtualenv/lib/python2.6/site-packages/django/db/models/query.py", line 1436, in insert_query
   return query.get_compiler(using=using).execute_sql(return_id)

 File "/.virtualenv/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 791, in execute_sql
   cursor = super(SQLInsertCompiler, self).execute_sql(None)

 File "/.virtualenv/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
   cursor.execute(sql, params)

 File "/.virtualenv/lib/python2.6/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
   return self.cursor.execute(query, args)

DatabaseError: invalid byte sequence for encoding "UTF8": 0xd020
 'REQUEST_METHOD': 'GET',

**Comment by klen** [comment]
Fix in version 0.2.99
